### ISSUE TITLE
How do I find the pipeline label id ?

### ISSUE THREAD

**Issue by madhurranjan** [gocd/documentation#104]
Hi,

Lets say I've instantiated a pipeline via the POST call. The response should tell me the pipeline label that has been kickstarted and I should be able to query on that pipeline label. I remember something similar was present earlier . Can you tell me if this requirement can be met with the current list of apis ? 

Thanks

**Comment by arvindsv** [comment]
Closing, since there's a [duplicate question](https://github.com/gocd/gocd/issues/990) in the gocd issue page. Questions should be asked on the mailing list. :P

Anyway, I'll answer there.
