### ISSUE TITLE
RE: Changing Windows client agent from default port

### ISSUE THREAD

**Issue by astrally2000** [gocd/documentation#149]
Guys,
I can't find what the parameter should be to specify a non-standard go server port for go agent on windows client. We have looked to configure a GO server servername:9153 and 9154 respectively.  I've tried switches /SERVERIP=servername:9134 and also /SERVERNAME=servername with /SERVERPORT=9154.

Ideally I'm trying to install via the chocolatey package and passing input arguments, as per https://chocolatey.org/packages/Thoughtworks.Go.Agent/14.3.0.0. 

Any thoughts whether non default port is supported?

**Comment by arvindsv** [comment]
The port cannot be changed during installation, I think. The [wrapper-agent.conf](https://github.com/gocd/gocd/blob/master/installers/agent/win/config/wrapper-agent.conf#L66) should have that value. Maybe you can change it and see?

**Comment by astrally2000** [comment]
Thanks very much Arvind, 
That has resolved my issue, 
I'm sorry I didn't see that parameter earlier, seems my initial google searching did not turn this page up either.
Cheers

**Comment by arvindsv** [comment]
You're welcome.
