### ISSUE TITLE
Task View extension message broken

### ISSUE THREAD

**Issue by ketan** [gocd/documentation#168]
On [this page](http://www.go.cd/documentation/developer/writing_go_plugins/task/version_1_0/view.html#request---from-the-server)

I think the expected request name should be `view`, instead of `execute`.

**Comment by arvindsv** [comment]
Right. I fixed it [directly](https://github.com/gocd/documentation/blob/master/developer/writing_go_plugins/task/version_1_0/view.md). Will show up in next build of this.
