### ISSUE TITLE
Instructions link[Registering agent with server] is broken

### ISSUE THREAD

**Issue by apoorvam** [gocd/documentation#192]
Instructions link(`here`) in section [Registering your agent with the server](http://www.go.cd/documentation/user/current/installation/install/agent/linux.html#registering-your-agent-with-the-server) is not working.

**Comment by arvindsv** [comment]
This should be [fixed](http://www.go.cd/documentation/user/current/installation/install/agent/linux.html#registering-your-agent-with-the-server) now.
