### ISSUE TITLE
Broken link in the installation page on Linux

### ISSUE THREAD

**Issue by samycici** [gocd/documentation#196]
In the page https://www.go.cd/documentation/user/current/installation/install/server/linux.html,  Installing Go agents link points to https://www.go.cd/documentation/user/current/installation/install/server/installing_go_agent.html  instead of
https://www.go.cd/documentation/user/current/installation/installing_go_agent.html

**Comment by arvindsv** [comment]
@samycici: Thank you very much! It is fixed.
