### ISSUE TITLE
No option to write custom shell script in a job

### ISSUE THREAD

**Issue by chinchang** [gocd/documentation#198]
If I am correct, right now a job can only be told to run a shell script in the material. But what if I want to write a script that should be run in that job without committing it the VCS (like jenkins)?

Any possible way of doing this?

**Comment by zabil** [comment]
There are better chances of getting help on our gocd user mailing list. 

Since you asked, there's convenience [plugin](https://github.com/gocd-contrib/script-executor-task) that allows you to run a series of command. (Go supports this too without a plugin for e.g. using bash -c)
